#!/usr/bin/env python3
"""Build LaTeX result tables from saved run summaries."""
from __future__ import annotations

import argparse
import re
import statistics
from pathlib import Path


def _parse_args() -> argparse.Namespace:
    """Parse CLI arguments."""

    p = argparse.ArgumentParser(description="Build consolidated paper tables.")
    p.add_argument("--results_root", type=str, required=True)
    p.add_argument("--output_dir", type=str, required=True)
    return p.parse_args()


def _parse_compact(summary_path: Path) -> dict[str, float] | None:
    """Extract metrics from the ``compact:`` line in a summary file."""

    if not summary_path.is_file():
        return None
    m = re.search(r"compact:\s*(.+)", summary_path.read_text())
    if not m:
        return None
    out: dict[str, float] = {}
    for kv in m.group(1).split(","):
        kv = kv.strip()
        if ":" not in kv:
            continue
        k, v = kv.split(":", 1)
        try:
            out[k.strip()] = float(v.strip())
        except ValueError:
            continue
    return out


def _fmt(x: float, nd: int = 3) -> str:
    """Format a scalar for LaTeX."""

    return f"{x:.{nd}f}"


def _fmt_pm(mean: float, std: float, nd: int = 3) -> str:
    """Format mean ± std for LaTeX."""

    return f"{mean:.{nd}f} $\\pm$ {std:.{nd}f}"


def _agg_seed_dirs(root: Path, pattern: str) -> tuple[float, float] | None:
    """Aggregate one metric key across seed dirs matching a glob prefix."""

    dirs = sorted(root.glob(pattern))
    vals: dict[str, list[float]] = {k: [] for k in ("rmse", "mae", "crps", "nll", "ece")}
    for d in dirs:
        m = _parse_compact(d / "paper_eval_summary.txt")
        if not m:
            continue
        for k in vals:
            if k in m:
                vals[k].append(m[k])
    if not vals["rmse"]:
        return None
    return tuple(
        (_fmt_pm(statistics.mean(vals[k]), statistics.stdev(vals[k]) if len(vals[k]) > 1 else 0.0)
         if len(vals[k]) > 1 else _fmt(statistics.mean(vals[k])))
        for k in ("rmse", "mae", "crps", "nll", "ece")
    )


def _row(label: str, m: dict[str, float], bold: bool = False) -> str:
    """One LaTeX table row."""

    prefix = "\\textbf{" if bold else ""
    suffix = "}" if bold else ""
    return (
        f"{prefix}{label}{suffix} & "
        f"{_fmt(m['rmse'])} & {_fmt(m['mae'])} & {_fmt(m['crps'])} & "
        f"{_fmt(m['nll'])} & {_fmt(m['ece'])} \\\\"
    )


def main() -> None:
    """Write Table 1 (main) and Table 2 (backbone) LaTeX files."""

    args = _parse_args()
    root = Path(args.results_root).resolve()
    out = Path(args.output_dir).resolve()
    out.mkdir(parents=True, exist_ok=True)

    # --- Table 1: probabilistic methods on SimVP ---
    rows_t1: list[str] = []
    static_rows = [
        ("Climatology + $\\sigma_{\\mathrm{clim}}$",
         {"rmse": 21.252, "mae": 16.940, "crps": 11.867, "nll": 4.475, "ece": 0.030}),
        ("Persistence + $\\sigma_{\\mathrm{clim}}$",
         {"rmse": 2.713, "mae": 1.435, "crps": 5.102, "nll": 3.983, "ece": 0.424}),
    ]
    for label, m in static_rows:
        rows_t1.append(_row(label, m))

    for label, sub in [
        ("MC Dropout ($N{=}10$, latent)", "baseline_mc_dropout_s42"),
        ("Deep Ensemble ($M{=}3$)", "baseline_deep_ensemble"),
        ("ProbWrapper + NLL from scratch", "simvp_prob_nll_scratch_mf_s42"),
    ]:
        m = _parse_compact(root / sub / "paper_eval_summary.txt")
        if m:
            rows_t1.append(_row(label, m))

    agg_beta = _agg_seed_dirs(root, "simvp_prob_beta_nll_scratch_mf_s*")
    if agg_beta:
        rows_t1.append(
            "ProbWrapper + $\\beta$-NLL from scratch ($\\beta{=}0.5$, 3 seeds) & "
            + " & ".join(agg_beta) + " \\\\"
        )
    else:
        m = _parse_compact(root / "simvp_prob_beta_nll_scratch_mf_s42" / "paper_eval_summary.txt")
        if m:
            rows_t1.append(_row(
                "ProbWrapper + $\\beta$-NLL from scratch ($\\beta{=}0.5$)", m))

    agg = _agg_seed_dirs(root, "simvp_prob_nll_ft_mf_s*")
    if agg:
        rows_t1.append(
            "\\textbf{Ours (ProbWrapper + CRPS$\\rightarrow$NLL, 3 seeds)} & "
            + " & ".join(agg) + " \\\\"
        )
    else:
        m = _parse_compact(root / "simvp_prob_nll_ft_mf_s42" / "paper_eval_summary.txt")
        if m:
            rows_t1.append(_row("\\textbf{Ours (ProbWrapper + CRPS$\\rightarrow$NLL)}", m, bold=False))

    t1_path = out / "table1_probabilistic_baselines.tex"
    with t1_path.open("w") as f:
        f.write("% Auto-generated by scripts/build_paper_tables.py\n")
        f.write("\\begin{table}[t]\n\\centering\n")
        f.write("\\caption{Probabilistic forecasting on WeatherBench t2m "
                "($5.625^\\circ$, 12$\\rightarrow$12, full test). "
                "All metrics in denormalized Kelvin unless dimensionless "
                "(NLL, ECE).}\n")
        f.write("\\label{tab:prob_baselines}\n")
        f.write("\\begin{tabular}{lccccc}\n\\toprule\n")
        f.write("Method & RMSE (K) & MAE (K) & CRPS (K) & NLL & ECE \\\\\n")
        f.write("\\midrule\n")
        f.write("\n".join(rows_t1))
        f.write("\n\\bottomrule\n\\end{tabular}\n\\end{table}\n")

    # --- Table 2: backbone generalization ---
    rows_t2: list[str] = []
    for label, sub in [
        ("SimVP-det (MSE)", None),
        ("ConvLSTM-det (MSE)", None),
        ("ProbWrapper + SimVP (CRPS$\\rightarrow$NLL, 3 seeds)", "simvp_agg"),
        ("ProbWrapper + ConvLSTM (CRPS$\\rightarrow$NLL, s42)",
         "convlstm_prob_nll_ft_mf_s42"),
        ("ProbWrapper + TAU (CRPS, s42)", "tau_prob_crps_mf_s42"),
    ]:
        if sub == "simvp_agg":
            agg2 = _agg_seed_dirs(root, "simvp_prob_nll_ft_mf_s*")
            if agg2:
                rows_t2.append(
                    f"{label} & " + " & ".join(agg2) + " \\\\"
                )
            continue
        if sub is None:
            continue
        m = _parse_compact(root / sub / "paper_eval_summary.txt")
        if m:
            rows_t2.append(_row(label, m))

    # Deterministic baselines (point metrics only).
    det_rows = [
        ("SimVP-det (MSE)", 1.079, 0.655),
        ("ConvLSTM-det (MSE)", 1.409, 0.859),
    ]
    for label, rmse, mae in det_rows:
        rows_t2.insert(
            0 if label.startswith("SimVP") else 1,
            f"{label} & {_fmt(rmse)} & {_fmt(mae)} & -- & -- & -- \\\\",
        )

    t2_path = out / "table2_backbone_generalization.tex"
    with t2_path.open("w") as f:
        f.write("% Auto-generated by scripts/build_paper_tables.py\n")
        f.write("\\begin{table}[t]\n\\centering\n")
        f.write("\\caption{Backbone-agnostic ProbWrapper (WeatherBench t2m, "
                "full test). Deterministic rows report point metrics only.}\n")
        f.write("\\label{tab:backbone}\n")
        f.write("\\begin{tabular}{lccccc}\n\\toprule\n")
        f.write("Backbone / method & RMSE (K) & MAE (K) & CRPS (K) & NLL & ECE \\\\\n")
        f.write("\\midrule\n")
        f.write("\n".join(rows_t2))
        f.write("\n\\bottomrule\n\\end{tabular}\n\\end{table}\n")

    # Plain-text rollup for zip / quick reference.
    rollup = out / "all_numbers.txt"
    with rollup.open("w") as f:
        f.write("TABLE 1 — Probabilistic baselines (SimVP family)\n")
        f.write("=" * 60 + "\n")
        for line in rows_t1:
            f.write(line.replace("\\textbf{", "").replace("}", "")
                       .replace(" \\\\", "") + "\n")
        f.write("\nTABLE 2 — Backbone generalization\n")
        f.write("=" * 60 + "\n")
        for line in rows_t2:
            f.write(line.replace(" \\\\", "") + "\n")

    print(f"Wrote {t1_path}")
    print(f"Wrote {t2_path}")
    print(f"Wrote {rollup}")

    # --- Table 3: z500 cross-variable generalization (SimVP / TAU) ---
    rows_t3: list[str] = []
    for label, sub in [
        ("ProbWrapper + SimVP (CRPS$\\rightarrow$NLL, s42)",
         "simvp_z500_prob_nll_ft_mf_s42"),
        ("ProbWrapper + TAU (CRPS$\\rightarrow$NLL, s42)",
         "tau_z500_prob_nll_ft_mf_s42"),
    ]:
        m = _parse_compact(root / sub / "paper_eval_summary.txt")
        if m:
            rows_t3.append(_row(label, m))

    agg_z = _agg_seed_dirs(root, "simvp_z500_prob_nll_ft_mf_s*")
    if agg_z:
        rows_t3.insert(
            0,
            "ProbWrapper + SimVP (CRPS$\\rightarrow$NLL, 3 seeds) & "
            + " & ".join(agg_z) + " \\\\",
        )

    if rows_t3:
        t3_path = out / "table3_z500_generalization.tex"
        with t3_path.open("w") as f:
            f.write("% Auto-generated by scripts/build_paper_tables.py\n")
            f.write("\\begin{table}[t]\n\\centering\n")
            f.write("\\caption{Cross-variable generalization on WeatherBench z500 "
                    "($5.625^\\circ$, 12$\\rightarrow$12, full test). "
                    "Metrics in denormalized geopotential units "
                    "(m$^2$s$^{-2}$) unless dimensionless (NLL, ECE).}\n")
            f.write("\\label{tab:z500}\n")
            f.write("\\begin{tabular}{lccccc}\n\\toprule\n")
            f.write("Method & RMSE & MAE & CRPS & NLL & ECE \\\\\n")
            f.write("\\midrule\n")
            f.write("\n".join(rows_t3))
            f.write("\n\\bottomrule\n\\end{tabular}\n\\end{table}\n")
        with rollup.open("a") as f:
            f.write("\nTABLE 3 — z500 generalization\n")
            f.write("=" * 60 + "\n")
            for line in rows_t3:
                f.write(line.replace(" \\\\", "") + "\n")
        print(f"Wrote {t3_path}")


if __name__ == "__main__":
    main()
