#!/usr/bin/env python3
"""Plot lead-time metrics and write a LaTeX table from per_leadtime.csv."""
from __future__ import annotations

import argparse
import csv
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt


def _parse_args() -> argparse.Namespace:
    """Parse CLI arguments for the lead-time plot helper."""

    p = argparse.ArgumentParser(
        description="Plot per lead-time metrics and emit a LaTeX table.",
    )
    p.add_argument("--csv", type=str, required=True,
                   help="Path to ``per_leadtime.csv``.")
    p.add_argument("--output_dir", type=str, default=None,
                   help="Where to write outputs. Defaults to the CSV's parent.")
    p.add_argument("--hours_per_step", type=int, default=6,
                   help="Time spacing of forecast frames. WeatherBench 5.625deg "
                        "is 6-hourly by default.")
    p.add_argument("--label", type=str, default="Ours",
                   help="Curve label / table column heading.")
    return p.parse_args()


def _read_rows(csv_path: Path) -> list[dict]:
    """Read the lead-time CSV into a list of dicts (one per row)."""

    rows = []
    with csv_path.open() as f:
        reader = csv.DictReader(f)
        for r in reader:
            rows.append({
                "leadtime": int(r["leadtime"]),
                "rmse": float(r["rmse"]),
                "mae": float(r["mae"]),
                "crps": float(r["crps"]),
                "nll": float(r["nll"]),
                "ece": float(r["ece"]),
            })
    rows.sort(key=lambda r: r["leadtime"])
    return rows


def _plot(rows: list[dict], hours_per_step: int, label: str,
          out_png: Path) -> None:
    """Render the 4-subplot lead-time figure (RMSE/MAE/CRPS/NLL + ECE).

    The 4 panels are arranged 2x2; ECE shares the bottom-right panel
    with NLL via a twin y-axis since they are on different scales.
    """

    # +1 because leadtime index 0 == first forecast step (1*hours_per_step).
    hours = [(r["leadtime"] + 1) * hours_per_step for r in rows]
    rmse = [r["rmse"] for r in rows]
    mae = [r["mae"] for r in rows]
    crps = [r["crps"] for r in rows]
    nll = [r["nll"] for r in rows]
    ece = [r["ece"] for r in rows]

    fig, axes = plt.subplots(2, 2, figsize=(11, 7.5), dpi=150)
    (ax_rmse, ax_crps), (ax_mae, ax_nll) = axes

    ax_rmse.plot(hours, rmse, "o-", label=label, color="C0")
    ax_rmse.set_ylabel("RMSE (K)")
    ax_rmse.set_title("RMSE vs lead-time")
    ax_rmse.grid(True, alpha=0.3)
    ax_rmse.legend()

    ax_crps.plot(hours, crps, "o-", label=label, color="C1")
    ax_crps.set_ylabel("CRPS (K)")
    ax_crps.set_title("CRPS vs lead-time")
    ax_crps.grid(True, alpha=0.3)
    ax_crps.legend()

    ax_mae.plot(hours, mae, "o-", label=label, color="C2")
    ax_mae.set_xlabel("Lead-time (hours)")
    ax_mae.set_ylabel("MAE (K)")
    ax_mae.set_title("MAE vs lead-time")
    ax_mae.grid(True, alpha=0.3)
    ax_mae.legend()

    ax_nll.plot(hours, nll, "o-", color="C3", label=f"NLL ({label})")
    ax_nll.set_xlabel("Lead-time (hours)")
    ax_nll.set_ylabel("NLL", color="C3")
    ax_nll.tick_params(axis="y", labelcolor="C3")
    ax_nll.grid(True, alpha=0.3)
    ax_nll_twin = ax_nll.twinx()
    ax_nll_twin.plot(hours, ece, "s--", color="C4", label=f"ECE ({label})")
    ax_nll_twin.set_ylabel("ECE", color="C4")
    ax_nll_twin.tick_params(axis="y", labelcolor="C4")
    ax_nll.set_title("NLL and ECE vs lead-time")
    # Combined legend across the twin axes.
    lines = ax_nll.get_lines() + ax_nll_twin.get_lines()
    ax_nll.legend(lines, [l.get_label() for l in lines], loc="upper left")

    fig.tight_layout()
    out_png.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_png, dpi=150, bbox_inches="tight")
    plt.close(fig)


def _emit_latex_table(rows: list[dict], hours_per_step: int,
                      out_tex: Path) -> None:
    """Write a LaTeX ``tabular`` summarising per lead-time + average."""

    def avg(key: str) -> float:
        return sum(r[key] for r in rows) / max(1, len(rows))

    out_tex.parent.mkdir(parents=True, exist_ok=True)
    with out_tex.open("w") as f:
        f.write("% Auto-generated by scripts/plot_leadtime.py\n")
        f.write("\\begin{tabular}{lccccc}\n")
        f.write("\\toprule\n")
        f.write("Lead-time & RMSE (K) & MAE (K) & CRPS (K) & NLL & ECE \\\\\n")
        f.write("\\midrule\n")
        for r in rows:
            hr = (r["leadtime"] + 1) * hours_per_step
            f.write(f"+{hr}h & {r['rmse']:.3f} & {r['mae']:.3f} & "
                    f"{r['crps']:.3f} & {r['nll']:.3f} & {r['ece']:.3f} \\\\\n")
        f.write("\\midrule\n")
        f.write(f"Average & {avg('rmse'):.3f} & {avg('mae'):.3f} & "
                f"{avg('crps'):.3f} & {avg('nll'):.3f} & "
                f"{avg('ece'):.3f} \\\\\n")
        f.write("\\bottomrule\n")
        f.write("\\end{tabular}\n")


def main() -> None:
    """Read the lead-time CSV, write the PNG figure and LaTeX table."""

    args = _parse_args()
    csv_path = Path(args.csv).resolve()
    if not csv_path.is_file():
        raise FileNotFoundError(f"--csv not found: {csv_path}")
    out_dir = Path(args.output_dir).resolve() if args.output_dir else csv_path.parent
    rows = _read_rows(csv_path)

    out_png = out_dir / "leadtime_curves.png"
    out_tex = out_dir / "leadtime_table.tex"
    _plot(rows, args.hours_per_step, args.label, out_png)
    _emit_latex_table(rows, args.hours_per_step, out_tex)

    print(f"Wrote figure -> {out_png}")
    print(f"Wrote table  -> {out_tex}")


if __name__ == "__main__":
    main()
